/**
 * Template Expansion — 90+ new high-quality government application templates.
 * Imported by seed.ts. All templates follow the existing schema.
 * Existing 77 templates preserved in seed.ts — this file is ADDITIVE.
 */
import { ApplicationTypeInsert } from '../types/database';

const G = 'gender';
type OT = ApplicationTypeInsert;

function p(officeType: string, appNameHindi: string, scenarioContext: string): string {
  return `आवेदन प्रकार: ${appNameHindi} (${officeType} कार्यालय)\nनीचे दिए गए फॉर्म डेटा का उपयोग करके एक संपूर्ण औपचारिक आवेदन पत्र तैयार करें।\n\nमहत्वपूर्ण निर्देश:\n${scenarioContext}\n\nसिस्टम प्रॉम्प्ट में वर्णित 7-भाग संरचना (सेवा में, विषय, सविनय निवेदन, घटना विवरण, अतः निवेदन, आभार, हस्ताक्षर) का सख्ती से पालन करें।\nघटना विवरण भाग में सभी तथ्यों को एक प्रवाहमय कालानुक्रमिक नैरेटिव अनुच्छेद में प्रस्तुत करें — बुलेट पॉइंट या सूची का प्रयोग न करें।\nप्रत्येक उल्लिखित व्यक्ति का पहली बार पूरा नाम, पिता/पति का नाम और गाँव अवश्य दें।\nआवेदक के लिंग (gender फील्ड) के अनुसार सभी व्याकरणिक रूपों का सही प्रयोग करें।\n\nआरोपी/विपक्षी की पहचान का प्रारूप:\n"[आरोपी का पूरा नाम], पिता/पति [आरोपी के पिता/पति का नाम], ग्राम [आरोपी का गाँव], थाना [आवेदक का थाना], जिला [आवेदक का जिला"\n\nफॉर्म डेटा:\n{{formDataSummary}}`;
}

function pa(officeType: string, appNameHindi: string, scenarioContext: string): string {
  return `आवेदन प्रकार: ${appNameHindi} (${officeType} कार्यालय)\nनीचे दिए गए फॉर्म डेटा का उपयोग करके एक संपूर्ण औपचारिक आवेदन पत्र तैयार करें।\n\nमहत्वपूर्ण निर्देश:\n${scenarioContext}\n\nसिस्टम प्रॉम्प्ट में वर्णित 7-भाग संरचना का पालन करें।\nदस्तावेज़/प्रमाण पत्र से संबंधित आवेदनों में घटना विवरण के स्थान पर आवेदन का औचित्य एवं संलग्न दस्तावेज़ों का विवरण दें।\nआवेदक के लिंग (gender) के अनुसार व्याकरणिक रूपों का सही प्रयोग करें।\n\nफॉर्म डेटा:\n{{formDataSummary}}`;
}

const B = ['applicant_name','parent_spouse_name','village','post','thana','district','state','mobile',G] as const;
function wb(fields: string[]): string { const s = new Set<string>(B); for (const f of fields) s.add(f); return JSON.stringify([...s]); }

const COURT_DISCLAIMER = 'यह एक प्रारूप मात्र है। जटिल कानूनी मामलों के लिए कृपया वकील से सलाह लें।';

export const NEW_TEMPLATES: ApplicationTypeInsert[] = [
  // THANA (+18 new: verbal abuse, home invasion, mobile theft, obstruction, stalking, liquor, gambling,
  //  tenant, social media threat, fake account, UPI fraud, bank fraud, livestock theft, accident,
  //  neighbour dispute, crop destruction, husband assault, missing child, witch-hunt)
  {office_type:'thana',name_hindi:'गाली-गलौज की शिकायत',name_english:'Verbal Abuse Complaint',keywords:JSON.stringify(['गाली','abuse','verbal','अपशब्द']),required_fields:wb(['incident_date','incident_time','location','abuse_details','accused_name','accused_father_name','accused_village','witnesses']),prompt_template:p('thana','गाली-गलौज की शिकायत','आरोपी द्वारा कब, कहाँ और किन शब्दों में गाली-गलौज की गई इसका कालानुक्रमिक विवरण दें। आरोपी की पूरी पहचान दें। गवाहों का उल्लेख करें। शांति भंग करने के विरुद्ध कार्रवाई का अनुरोध करें।'),requires_legal_disclaimer:0,disclaimer_text:null},
  {office_type:'thana',name_hindi:'घर में घुसकर मारपीट की शिकायत',name_english:'Home Invasion Assault Complaint',keywords:JSON.stringify(['घर','trespass','हमला','घरेलू']),required_fields:wb(['incident_date','incident_time','location','incident_details','accused_names','accused_father_name','accused_village','injury_details','weapons_used','witnesses','property_damage']),prompt_template:p('thana','घर में घुसकर मारपीट की शिकायत','आरोपी कब और कैसे घर में घुसे, क्या कहा और कैसे मारपीट की इसका विस्तृत विवरण दें। प्रत्येक आरोपी की पूरी पहचान दें। किस हथियार का प्रयोग हुआ और चोटों का विवरण दें। गवाहों का उल्लेख करें। प्राथमिकी दर्ज करने का अनुरोध करें।'),requires_legal_disclaimer:0,disclaimer_text:null},
  {office_type:'thana',name_hindi:'मोबाइल चोरी की शिकायत',name_english:'Mobile Phone Theft Complaint',keywords:JSON.stringify(['मोबाइल','phone','चोरी','stolen']),required_fields:wb(['incident_date','incident_time','location','phone_brand','phone_model','imei_number','phone_number','accused_name','accused_father_name','accused_village','witnesses']),prompt_template:p('thana','मोबाइल चोरी की शिकायत','मोबाइल का ब्रांड, मॉडल, IMEI नंबर और फोन नंबर बताएं। कब और कहाँ चोरी हुआ बताएं। संदिग्ध की पहचान दें। CCTV और गवाहों का उल्लेख करें। प्राथमिकी दर्ज कर मोबाइल बरामदगी का अनुरोध करें।'),requires_legal_disclaimer:0,disclaimer_text:null},
  {office_type:'thana',name_hindi:'रास्ता रोकने की शिकायत',name_english:'Obstruction of Passage Complaint',keywords:JSON.stringify(['रास्ता','passage','रोकना','blockage']),required_fields:wb(['incident_date','location','route_description','accused_name','accused_father_name','accused_village','obstruction_details','duration','impact','witnesses']),prompt_template:p('thana','रास्ता रोकने की शिकायत','किस रास्ते को, किसने, कब से और कैसे रोका है इसका विवरण दें। रास्ते का विवरण और उपयोग का इतिहास बताएं। आरोपी की पूरी पहचान दें। आवागमन पर प्रभाव बताएं। पुलिस हस्तक्षेप का अनुरोध करें।'),requires_legal_disclaimer:0,disclaimer_text:null},
  {office_type:'thana',name_hindi:'पीछा करने की शिकायत',name_english:'Stalking Complaint',keywords:JSON.stringify(['पीछा','stalking','follow','harassment']),required_fields:wb(['incident_date','location','accused_name','accused_father_name','accused_village','stalking_details','duration','impact','evidence']),prompt_template:p('thana','पीछा करने की शिकायत','आरोपी कब से और कैसे पीछा कर रहा है इसका कालानुक्रमिक विवरण दें। आरोपी की पूरी पहचान दें। मानसिक प्रभाव और सबूत बताएं। सुरक्षा और कार्रवाई का अनुरोध करें।'),requires_legal_disclaimer:0,disclaimer_text:null},
  {office_type:'thana',name_hindi:'अवैध शराब बिक्री की शिकायत',name_english:'Illegal Liquor Sale Complaint',keywords:JSON.stringify(['शराब','liquor','अवैध','illegal','बिक्री']),required_fields:wb(['location','accused_name','accused_father_name','accused_village','activity_details','since_when','impact','witnesses']),prompt_template:p('thana','अवैध शराब बिक्री की शिकायत','कहाँ और कब से अवैध शराब बिक्री हो रही है बताएं। आरोपी की पहचान दें। स्थानीय निवासियों पर दुष्प्रभाव बताएं। पुलिस से छापेमारी और कार्रवाई का अनुरोध करें।'),requires_legal_disclaimer:0,disclaimer_text:null},
  {office_type:'thana',name_hindi:'जुआ खेलने/खिलाने की शिकायत',name_english:'Gambling Complaint',keywords:JSON.stringify(['जुआ','gambling','सट्टा','betting']),required_fields:wb(['location','accused_name','accused_father_name','accused_village','activity_details','since_when','impact','witnesses']),prompt_template:p('thana','जुआ खेलने/खिलाने की शिकायत','कहाँ और कब से जुआ/सट्टा संचालित हो रहा है बताएं। आयोजक की पहचान दें। परिवारों पर आर्थिक-सामाजिक दुष्प्रभाव बताएं। कार्रवाई का अनुरोध करें।'),requires_legal_disclaimer:0,disclaimer_text:null},
  {office_type:'thana',name_hindi:'सोशल मीडिया पर धमकी की शिकायत',name_english:'Social Media Threat Complaint',keywords:JSON.stringify(['सोशल मीडिया','facebook','whatsapp','धमकी','threat','online']),required_fields:wb(['incident_date','platform','accused_name','accused_father_name','accused_village','threat_details','evidence_screenshots']),prompt_template:p('thana','सोशल मीडिया पर धमकी की शिकायत','किस प्लेटफॉर्म पर, किसने और कब धमकी दी बताएं। आरोपी का नाम, पिता का नाम, गाँव और ऑनलाइन प्रोफाइल दें। स्क्रीनशॉट सबूत का उल्लेख करें। IT Act के तहत प्राथमिकी का अनुरोध करें।'),requires_legal_disclaimer:0,disclaimer_text:null},
  {office_type:'thana',name_hindi:'फर्जी सोशल मीडिया अकाउंट की शिकायत',name_english:'Fake Social Media Account Complaint',keywords:JSON.stringify(['फर्जी','fake','account','impersonation']),required_fields:wb(['incident_date','platform','fake_account_details','real_account_details','accused_name','accused_father_name','accused_village','impact','evidence']),prompt_template:p('thana','फर्जी सोशल मीडिया अकाउंट की शिकायत','किस प्लेटफॉर्म पर किसके नाम से फर्जी अकाउंट बनाया गया बताएं। आरोपी की पहचान और सबूत दें। प्रतिष्ठा पर प्रभाव बताएं। IT Act के तहत कार्रवाई का अनुरोध करें।'),requires_legal_disclaimer:0,disclaimer_text:null},
  {office_type:'thana',name_hindi:'UPI धोखाधड़ी की शिकायत',name_english:'UPI Fraud Complaint',keywords:JSON.stringify(['UPI','fraud','धोखाधड़ी','payment']),required_fields:wb(['incident_date','platform','transaction_amount','transaction_id','accused_upi_id','accused_name','accused_father_name','accused_village','incident_details']),prompt_template:p('thana','UPI धोखाधड़ी की शिकायत','किस ऐप पर, कब और कितनी राशि की धोखाधड़ी हुई बताएं। ट्रांजेक्शन ID और आरोपी का UPI ID दें। साइबर सेल से कार्रवाई का अनुरोध करें।'),requires_legal_disclaimer:0,disclaimer_text:null},
  {office_type:'thana',name_hindi:'बैंक धोखाधड़ी की शिकायत',name_english:'Bank Fraud Complaint',keywords:JSON.stringify(['बैंक','bank','fraud','unauthorized']),required_fields:wb(['incident_date','bank_name','account_number_last4','transaction_amount','transaction_id','accused_name','accused_father_name','accused_village','incident_details']),prompt_template:p('thana','बैंक धोखाधड़ी की शिकायत','किस बैंक और खाते से धोखाधड़ी हुई बताएं। राशि, तारीख और ट्रांजेक्शन ID दें। संदिग्ध की पहचान दें। प्राथमिकी और राशि वापसी का अनुरोध करें।'),requires_legal_disclaimer:0,disclaimer_text:null},
  {office_type:'thana',name_hindi:'पशु चोरी की शिकायत',name_english:'Livestock Theft Complaint',keywords:JSON.stringify(['पशु','livestock','cattle','चोरी']),required_fields:wb(['incident_date','incident_time','location','animal_type','animal_count','animal_description','accused_name','accused_father_name','accused_village','witnesses']),prompt_template:p('thana','पशु चोरी की शिकायत','चुराए गए पशु का प्रकार, संख्या और पहचान बताएं। कब और कहाँ से चोरी हुआ बताएं। संदिग्ध और गवाहों का उल्लेख करें। प्राथमिकी और बरामदगी का अनुरोध करें।'),requires_legal_disclaimer:0,disclaimer_text:null},
  {office_type:'thana',name_hindi:'वाहन दुर्घटना की शिकायत',name_english:'Vehicle Accident Complaint',keywords:JSON.stringify(['दुर्घटना','accident','vehicle','टक्कर']),required_fields:wb(['incident_date','incident_time','location','vehicle_type','vehicle_number','accused_name','accused_father_name','accused_village','injury_details','damage_details','witnesses']),prompt_template:p('thana','वाहन दुर्घटना की शिकायत','दुर्घटना कब, कहाँ और कैसे हुई बताएं। वाहन का प्रकार और नंबर दें। आरोपी चालक की पहचान दें। चोट और क्षति का विवरण दें। प्राथमिकी और कार्रवाई का अनुरोध करें।'),requires_legal_disclaimer:0,disclaimer_text:null},
  {office_type:'thana',name_hindi:'पड़ोसी विवाद की शिकायत',name_english:'Neighbour Dispute Complaint',keywords:JSON.stringify(['पड़ोसी','neighbour','dispute','विवाद']),required_fields:wb(['incident_date','location','accused_name','accused_father_name','accused_village','dispute_details','previous_attempts','witnesses']),prompt_template:p('thana','पड़ोसी विवाद की शिकायत','पड़ोसी के साथ विवाद का कारण और विवरण दें। आरोपी की पहचान और पूर्व समझौता प्रयास बताएं। गवाहों का उल्लेख करें। शांति व्यवस्था का अनुरोध करें।'),requires_legal_disclaimer:0,disclaimer_text:null},
  {office_type:'thana',name_hindi:'फसल नष्ट करने की शिकायत',name_english:'Crop Destruction Complaint',keywords:JSON.stringify(['फसल','crop','destruction','खेत','नुकसान']),required_fields:wb(['incident_date','location','crop_type','land_area','damage_estimate','accused_name','accused_father_name','accused_village','witnesses']),prompt_template:p('thana','फसल नष्ट करने की शिकायत','किसकी फसल, कहाँ, कब और कैसे नष्ट की गई बताएं। फसल प्रकार और हानि का अनुमान दें। आरोपी की पहचान दें। प्राथमिकी और मुआवजे का अनुरोध करें।'),requires_legal_disclaimer:0,disclaimer_text:null},
  {office_type:'thana',name_hindi:'पति द्वारा मारपीट की शिकायत',name_english:'Husband Assault Complaint',keywords:JSON.stringify(['पति','husband','मारपीट','domestic']),required_fields:wb(['incident_date','location','accused_name','accused_father_name','accused_village','marriage_date','incident_details','injury_details','witnesses','prior_complaints']),prompt_template:p('thana','पति द्वारा मारपीट की शिकायत','विवाह तिथि और पति के साथ विवाद का कारण बताएं। मारपीट का कालानुक्रमिक विवरण दें। चोटों और चिकित्सीय रिपोर्ट का उल्लेख करें। घरेलू हिंसा अधिनियम के तहत कार्रवाई का अनुरोध करें।'),requires_legal_disclaimer:0,disclaimer_text:null},
  {office_type:'thana',name_hindi:'बच्चा गुमशुदगी रिपोर्ट',name_english:'Missing Child Report',keywords:JSON.stringify(['बच्चा','child','missing','गुमशुदा']),required_fields:wb(['child_name','age','gender','height','clothing_last_seen','last_seen_date','last_seen_location','parent_name','relation_to_child','photo_description']),prompt_template:p('thana','बच्चा गुमशुदगी रिपोर्ट','गुमशुदा बच्चे का नाम, आयु, कद, रंग, कपड़े और पहचान चिह्न बताएं। अंतिम बार कब, कहाँ और किसके साथ देखा गया बताएं। तत्काल तलाशी और प्राथमिकी का अनुरोध करें।'),requires_legal_disclaimer:0,disclaimer_text:null},
  {office_type:'thana',name_hindi:'डायन प्रताड़ना की शिकायत',name_english:'Witch-Hunt Harassment Complaint',keywords:JSON.stringify(['डायन','witch','प्रताड़ना','अंधविश्वास']),required_fields:wb(['incident_date','location','victim_name','accused_names','accused_father_name','accused_village','incident_details','duration','witnesses','threat_level']),prompt_template:p('thana','डायन प्रताड़ना की शिकायत','पीड़िता का नाम और आरोपियों की पहचान दें। कब से और कैसे डायन कहकर प्रताड़ित किया जा रहा है बताएं। जान-माल के खतरे का उल्लेख करें। डायन प्रथा उन्मूलन अधिनियम के तहत कार्रवाई का अनुरोध करें।'),requires_legal_disclaimer:0,disclaimer_text:null},
  {office_type:'thana',name_hindi:'किरायेदार द्वारा परेशान करने की शिकायत',name_english:'Tenant Harassment Complaint',keywords:JSON.stringify(['किरायेदार','tenant','किराया','परेशान']),required_fields:wb(['incident_date','location','accused_name','accused_father_name','accused_village','rent_details','complaint_details','witnesses']),prompt_template:p('thana','किरायेदार द्वारा परेशान करने की शिकायत','किरायेदार का नाम और पिता का नाम बताएं। कब से और कैसे परेशान कर रहा है बताएं। किराया समझौते का विवरण दें। पुलिस हस्तक्षेप का अनुरोध करें।'),requires_legal_disclaimer:0,disclaimer_text:null},

  // CO (+15): jamabandi, demarcation, succession mutation, post-sale mutation, area correction,
  //  map correction, settlement, revenue receipt, land use cert, illegal possession removal,
  //  govt land encroachment, non-agri land, partition jamabandi, online record error, land NOC, sale deed reg
  {office_type:'co',name_hindi:'जमाबंदी सुधार आवेदन',name_english:'Jamabandi Correction',keywords:JSON.stringify(['जमाबंदी','jamabandi','correction','सुधार','भूमि','land','रिकॉर्ड']),required_fields:wb(['khata_number','khasra_number','mouja_name','error_description','correct_info','supporting_documents','original_owner_name','relation_to_owner']),prompt_template:pa('co','जमाबंदी सुधार आवेदन','खसरा/खाता नंबर और मौजा बताएं। क्या त्रुटि है और सही जानकारी दें। यदि पूर्वज के नाम पर है तो original_owner_name और relation_to_owner का उपयोग करें। सुधार का अनुरोध करें।'),requires_legal_disclaimer:0,disclaimer_text:null},
  {office_type:'co',name_hindi:'सीमांकन आवेदन',name_english:'Land Demarcation Application',keywords:JSON.stringify(['सीमांकन','demarcation','boundary','सीमा']),required_fields:wb(['khata_number','khasra_number','mouja_name','boundary_description','neighbour_names','reason','original_owner_name','relation_to_owner']),prompt_template:pa('co','सीमांकन आवेदन','खसरा/खाता नंबर और मौजा बताएं। सीमांकन का कारण और पड़ोसी भू-स्वामी बताएं। राजस्व निरीक्षक/अमीन द्वारा सीमांकन का अनुरोध करें।'),requires_legal_disclaimer:0,disclaimer_text:null},
  {office_type:'co',name_hindi:'उत्तराधिकार दाखिल-खारिज',name_english:'Succession Mutation',keywords:JSON.stringify(['उत्तराधिकार','succession','mutation','दाखिल-खारिज']),required_fields:wb(['khata_number','khasra_number','mouja_name','deceased_name','death_date','relation_to_deceased','succession_document','other_heirs','original_owner_name','relation_to_owner']),prompt_template:pa('co','उत्तराधिकार दाखिल-खारिज','मृतक का नाम, मृत्यु तिथि और आवेदक का संबंध बताएं। खसरा/खाता और मौजा दें। उत्तराधिकार प्रमाण पत्र का उल्लेख करें। नामांतरण का अनुरोध करें।'),requires_legal_disclaimer:0,disclaimer_text:null},
  {office_type:'co',name_hindi:'विक्रय पत्र के बाद दाखिल-खारिज',name_english:'Post-Sale Mutation',keywords:JSON.stringify(['विक्रय','sale','deed','mutation','बैनामा']),required_fields:wb(['khata_number','khasra_number','mouja_name','deed_number','deed_date','seller_name','buyer_name','consideration_amount','supporting_documents']),prompt_template:pa('co','विक्रय पत्र के बाद दाखिल-खारिज','खसरा/खाता और मौजा बताएं। बैनामा तिथि, संख्या और राशि दें। विक्रेता-क्रेता का नाम बताएं। क्रेता का नाम दर्ज करने का अनुरोध करें।'),requires_legal_disclaimer:0,disclaimer_text:null},
  {office_type:'co',name_hindi:'रकबा सुधार आवेदन',name_english:'Land Area Correction',keywords:JSON.stringify(['रकबा','area','correction','भूमि']),required_fields:wb(['khata_number','khasra_number','mouja_name','recorded_area','actual_area','correction_reason','supporting_documents']),prompt_template:pa('co','रकबा सुधार आवेदन','खसरा/खाता और मौजा बताएं। दर्ज रकबा और वास्तविक रकबा दोनों बताएं। सुधार का कारण और प्रमाण दें। रकबा सुधार का अनुरोध करें।'),requires_legal_disclaimer:0,disclaimer_text:null},
  {office_type:'co',name_hindi:'नक्शा सुधार आवेदन',name_english:'Map Correction',keywords:JSON.stringify(['नक्शा','map','correction','भूमि']),required_fields:wb(['khata_number','khasra_number','mouja_name','error_description','correct_info','supporting_documents']),prompt_template:pa('co','नक्शा सुधार आवेदन','खसरा/खाता और मौजा बताएं। नक्शे में क्या त्रुटि है और सही जानकारी दें।प्रमाण दस्तावेज़ बताएं। नक्शा सुधार का अनुरोध करें।'),requires_legal_disclaimer:0,disclaimer_text:null},
  {office_type:'co',name_hindi:'बंदोबस्ती आवेदन',name_english:'Land Settlement Application',keywords:JSON.stringify(['बंदोबस्ती','settlement','land','भूमि']),required_fields:wb(['mouja_name','land_description','area','possession_since','cultivation_details','supporting_documents']),prompt_template:pa('co','बंदोबस्ती आवेदन','मौजा और भूमि का विवरण दें। कब से कब्जा/खेती है बताएं। कृषि विवरण और दस्तावेज़ बताएं। बंदोबस्ती का अनुरोध करें।'),requires_legal_disclaimer:0,disclaimer_text:null},
  {office_type:'co',name_hindi:'भू-राजस्व रसीद निर्गत आवेदन',name_english:'Land Revenue Receipt',keywords:JSON.stringify(['राजस्व','revenue','receipt','रसीद','भूमि कर']),required_fields:wb(['khata_number','khasra_number','mouja_name','payment_year','payment_amount','purpose']),prompt_template:pa('co','भू-राजस्व रसीद निर्गत आवेदन','खसरा/खाता और मौजा बताएं। किस वर्ष का राजस्व और राशि बताएं। रसीद का प्रयोजन बताएं।रसीद निर्गत करने का अनुरोध करें।'),requires_legal_disclaimer:0,disclaimer_text:null},
  {office_type:'co',name_hindi:'भूमि उपयोग प्रमाण पत्र',name_english:'Land Use Certificate',keywords:JSON.stringify(['भूमि','land use','certificate','प्रमाण पत्र']),required_fields:wb(['khata_number','khasra_number','mouja_name','current_use','purpose','supporting_documents']),prompt_template:pa('co','भूमि उपयोग प्रमाण पत्र','खसरा/खाता और मौजा बताएं। भूमि का वर्तमान उपयोग बताएं।प्रमाण पत्र किस प्रयोजन हेतु चाहिए बताएं।प्रमाण पत्र निर्गत करने का अनुरोध करें।'),requires_legal_disclaimer:0,disclaimer_text:null},
  {office_type:'co',name_hindi:'अवैध कब्जा हटाने का आवेदन',name_english:'Illegal Possession Removal',keywords:JSON.stringify(['कब्जा','possession','अवैध','बेदखली','जमीन','भूमि','land']),required_fields:wb(['khata_number','khasra_number','mouja_name','encroacher_name','encroacher_father_name','encroacher_village','encroachment_details','since_when','previous_complaints']),prompt_template:p('co','अवैध कब्जा हटाने का आवेदन','खसरा/खाता और मौजा बताएं। अतिक्रमणकर्ता की पहचान दें। कब से और कैसे कब्जा है बताएं।पूर्व शिकायतों का उल्लेख करें। बेदखली की कार्रवाई का अनुरोध करें।'),requires_legal_disclaimer:0,disclaimer_text:null},
  {office_type:'co',name_hindi:'सरकारी जमीन अतिक्रमण शिकायत',name_english:'Govt Land Encroachment',keywords:JSON.stringify(['सरकारी','government','land','अतिक्रमण','सार्वजनिक','जमीन','कब्जा','भूमि']),required_fields:wb(['mouja_name','khata_number','khasra_number','encroacher_name','encroacher_father_name','encroacher_village','encroachment_details','since_when','land_type','impact']),prompt_template:p('co','सरकारी जमीन अतिक्रमण शिकायत','किस सरकारी भूमि पर अतिक्रमण हुआ है बताएं।खसरा/खाता और मौजा दें।अतिक्रमणकर्ता की पहचान दें। तत्काल कार्रवाई का अनुरोध करें।'),requires_legal_disclaimer:0,disclaimer_text:null},
  {office_type:'co',name_hindi:'गैरमजरुआ भूमि शिकायत',name_english:'Non-Agricultural Land Complaint',keywords:JSON.stringify(['गैरमजरुआ','non-agricultural','land','शिकायत']),required_fields:wb(['khata_number','khasra_number','mouja_name','land_type','violation_details','since_when']),prompt_template:p('co','गैरमजरुआ भूमि शिकायत','खसरा/खाता और मौजा बताएं। भूमि का मूल वर्गीकरण और दुरुपयोग का विवरण दें। कब से और किसके द्वारा हो रहा है बताएं। जाँच कर कार्रवाई का अनुरोध करें।'),requires_legal_disclaimer:0,disclaimer_text:null},
  {office_type:'co',name_hindi:'विभाजन के बाद पृथक जमाबंदी',name_english:'Post-Partition Separate Jamabandi',keywords:JSON.stringify(['विभाजन','partition','जमाबंदी','बंटवारा']),required_fields:wb(['khata_number','khasra_number','mouja_name','partition_date','family_members','share_details','partition_document']),prompt_template:pa('co','विभाजन के बाद पृथक जमाबंदी','मूल खसरा/खाता और मौजा बताएं। विभाजन तिथि और हिस्सेदारों का विवरण दें।पृथक जमाबंदी खोलने का अनुरोध करें।'),requires_legal_disclaimer:0,disclaimer_text:null},
  {office_type:'co',name_hindi:'ऑनलाइन भूमि रिकॉर्ड त्रुटि सुधार',name_english:'Online Land Record Error Correction',keywords:JSON.stringify(['ऑनलाइन','online','land record','error','डिजिटल']),required_fields:wb(['khata_number','khasra_number','mouja_name','portal_name','error_description','correct_info']),prompt_template:pa('co','ऑनलाइन भूमि रिकॉर्ड त्रुटि सुधार','किस पोर्टल पर त्रुटि है और खसरा/खाता बताएं।गलत और सही जानकारी दें। ऑनलाइन और ऑफलाइन रिकॉर्ड में सुधार का अनुरोध करें।'),requires_legal_disclaimer:0,disclaimer_text:null},
  {office_type:'co',name_hindi:'भूमि NOC आवेदन',name_english:'Land NOC Application',keywords:JSON.stringify(['NOC','no objection','भूमि','land']),required_fields:wb(['khata_number','khasra_number','mouja_name','purpose','land_area','period_of_ownership']),prompt_template:pa('co','भूमि NOC आवेदन','खसरा/खाता और मौजा बताएं। किस प्रयोजन हेतु NOC चाहिए बताएं। भूमि क्षेत्रफल और स्वामित्व अवधि दें। अनापत्ति प्रमाण पत्र निर्गत करने का अनुरोध करें।'),requires_legal_disclaimer:0,disclaimer_text:null},
  {office_type:'co',name_hindi:'विक्रय पत्र पंजीकरण आवेदन',name_english:'Sale Deed Registration',keywords:JSON.stringify(['विक्रय','sale','deed','registration','पंजीकरण']),required_fields:wb(['khata_number','khasra_number','mouja_name','seller_name','buyer_name','consideration_amount','deed_preparation_date']),prompt_template:pa('co','विक्रय पत्र पंजीकरण आवेदन','खसरा/खाता और मौजा बताएं।विक्रेता-क्रेता का नाम और राशि दें। विक्रय पत्र पंजीकृत करने का अनुरोध करें।'),requires_legal_disclaimer:0,disclaimer_text:null},

  // BLOCK (+10) + BDO (+10)
  {office_type:'block',name_hindi:'PM आवास योजना आवेदन',name_english:'PM Awas Yojana Application',keywords:JSON.stringify(['आवास','housing','PM','योजना','ग्रामीण']),required_fields:wb(['scheme_name','current_house_type','annual_income','family_members','bpl_status','land_ownership','bank_account_last4']),prompt_template:pa('block','PM आवास योजना आवेदन','किस योजना के अंतर्गत आवेदन है बताएं।वर्तमान आवास स्थिति, परिवार सदस्य और आय बताएं।BPL स्थिति और भूमि स्वामित्व दें।पात्रतानुसार आवास का लाभ प्रदान करने का अनुरोध करें।'),requires_legal_disclaimer:0,disclaimer_text:null},
  {office_type:'block',name_hindi:'नया राशन कार्ड आवेदन',name_english:'New Ration Card Application',keywords:JSON.stringify(['राशन','ration','card','नया','खाद्य']),required_fields:wb(['family_members','member_details','annual_income','bpl_status','caste','previous_card','bank_account_last4']),prompt_template:pa('block','नया राशन कार्ड आवेदन','परिवार के सदस्यों का नाम, आयु बताएं।वार्षिक आय और BPL स्थिति दें। खाद्य विभाग से नया राशन कार्ड निर्गत करने का अनुरोध करें।'),requires_legal_disclaimer:0,disclaimer_text:null},
  {office_type:'block',name_hindi:'राशन कार्ड में नाम जोड़ने हेतु आवेदन',name_english:'Ration Card Add Member',keywords:JSON.stringify(['राशन','ration','add','जोड़ना','member']),required_fields:wb(['ration_card_number','new_member_name','new_member_age','relation_to_head','reason']),prompt_template:pa('block','राशन कार्ड में नाम जोड़ने हेतु आवेदन','राशन कार्ड नंबर और मुखिया का नाम बताएं।जोड़े जाने वाले सदस्य का नाम, आयु और संबंध बताएं।नाम जोड़ने का अनुरोध करें।'),requires_legal_disclaimer:0,disclaimer_text:null},
  {office_type:'block',name_hindi:'राशन कार्ड से नाम हटाने हेतु आवेदन',name_english:'Ration Card Remove Member',keywords:JSON.stringify(['राशन','ration','remove','हटाना']),required_fields:wb(['ration_card_number','member_name','removal_reason']),prompt_template:pa('block','राशन कार्ड से नाम हटाने हेतु आवेदन','राशन कार्ड नंबर और मुखिया का नाम बताएं।हटाए जाने वाले सदस्य का नाम और कारण बताएं।नाम हटाने का अनुरोध करें।'),requires_legal_disclaimer:0,disclaimer_text:null},
  {office_type:'block',name_hindi:'जन्म प्रमाण पत्र आवेदन',name_english:'Birth Certificate Application',keywords:JSON.stringify(['जन्म','birth','certificate','प्रमाण पत्र']),required_fields:wb(['child_name','birth_date','birth_place','father_name','mother_name','hospital_name']),prompt_template:pa('block','जन्म प्रमाण पत्र आवेदन','बच्चे का नाम, जन्म तिथि और स्थान बताएं।माता-पिता का नाम और अस्पताल का नाम दें। जन्म प्रमाण पत्र निर्गत करने का अनुरोध करें।'),requires_legal_disclaimer:0,disclaimer_text:null},
  {office_type:'block',name_hindi:'परिवार रजिस्टर नकल आवेदन',name_english:'Family Register Copy',keywords:JSON.stringify(['परिवार','family','register','नकल']),required_fields:wb(['family_head_name','village','purpose']),prompt_template:pa('block','परिवार रजिस्टर नकल आवेदन','परिवार मुखिया का नाम और गाँव बताएं।किस प्रयोजन हेतु नकल चाहिए बताएं। परिवार रजिस्टर की सत्यापित प्रति का अनुरोध करें।'),requires_legal_disclaimer:0,disclaimer_text:null},
  {office_type:'block',name_hindi:'वोटर ID पंजीकरण आवेदन',name_english:'Voter ID Registration',keywords:JSON.stringify(['वोटर','voter','पहचान','चुनाव','election','मतदाता','निर्वाचन']),required_fields:wb(['dob','residence_since','previous_address','family_voter_details']),prompt_template:pa('block','वोटर ID पंजीकरण आवेदन','जन्म तिथि, वर्तमान पता और कितने समय से निवास है बताएं।पूर्व पता और परिवार के मतदाता विवरण दें।नया मतदाता पहचान पत्र निर्गत करने का अनुरोध करें।'),requires_legal_disclaimer:0,disclaimer_text:null},
  {office_type:'block',name_hindi:'वोटर ID सुधार आवेदन',name_english:'Voter ID Correction',keywords:JSON.stringify(['वोटर','voter','correction','सुधार','चुनाव']),required_fields:wb(['voter_id_number','correction_type','current_info','correct_info']),prompt_template:pa('block','वोटर ID सुधार आवेदन','मतदाता पहचान पत्र संख्या और सुधार प्रकार बताएं।गलत और सही जानकारी दें। मतदाता सूची में सुधार का अनुरोध करें।'),requires_legal_disclaimer:0,disclaimer_text:null},
  {office_type:'block',name_hindi:'नया पानी कनेक्शन आवेदन',name_english:'New Water Connection',keywords:JSON.stringify(['पानी','water','connection','नया']),required_fields:wb(['address','purpose','family_size','nearby_main']),prompt_template:pa('block','नया पानी कनेक्शन आवेदन','पता और कनेक्शन का प्रयोजन बताएं।परिवार सदस्य संख्या और नजदीकी मुख्य पाइपलाइन बताएं।नया पानी कनेक्शन प्रदान करने का अनुरोध करें।'),requires_legal_disclaimer:0,disclaimer_text:null},
  {office_type:'block',name_hindi:'विवाह पंजीकरण आवेदन',name_english:'Marriage Registration',keywords:JSON.stringify(['विवाह','marriage','registration','शादी']),required_fields:wb(['groom_name','bride_name','marriage_date','marriage_place','witness1','witness2']),prompt_template:pa('block','विवाह पंजीकरण आवेदन','वर और वधू का नाम, विवाह तिथि और स्थान बताएं। दो गवाहों का नाम दें।विवाह पंजीकरण का अनुरोध करें।'),requires_legal_disclaimer:0,disclaimer_text:null},
  {office_type:'bdo',name_hindi:'मनरेगा जॉब कार्ड सुधार',name_english:'MGNREGA Job Card Correction',keywords:JSON.stringify(['मनरेगा','job card','सुधार','correction']),required_fields:wb(['job_card_number','correction_type','current_info','correct_info','village_panchayat']),prompt_template:pa('bdo','मनरेगा जॉब कार्ड सुधार','जॉब कार्ड नंबर और ग्राम पंचायत बताएं।क्या सुधार चाहिए और गलत/सही जानकारी दें।जॉब कार्ड में सुधार का अनुरोध करें।'),requires_legal_disclaimer:0,disclaimer_text:null},
  {office_type:'bdo',name_hindi:'शौचालय निर्माण आवेदन',name_english:'Toilet Construction Application',keywords:JSON.stringify(['शौचालय','toilet','निर्माण','स्वच्छता']),required_fields:wb(['scheme_name','current_facility','family_members','bpl_status','land_availability','bank_account_last4']),prompt_template:pa('bdo','शौचालय निर्माण आवेदन','किस योजना के अंतर्गत आवेदन है बताएं।वर्तमान सुविधा और परिवार सदस्य बताएं।BPL स्थिति दें।शौचालय निर्माण स्वीकृत करने का अनुरोध करें।'),requires_legal_disclaimer:0,disclaimer_text:null},
  {office_type:'bdo',name_hindi:'दिव्यांग पेंशन आवेदन',name_english:'Disability Pension',keywords:JSON.stringify(['दिव्यांग','disabled','pension','पेंशन','वृद्धा','विधवा','सामाजिक']),required_fields:wb(['disability_type','disability_percentage','certificate_number','age','income','bank_account_last4']),prompt_template:pa('bdo','दिव्यांग पेंशन आवेदन','विकलांगता प्रकार, प्रतिशत और प्रमाण पत्र संख्या बताएं।आयु और आय दें।पात्रतानुसार पेंशन स्वीकृत करने का अनुरोध करें।'),requires_legal_disclaimer:0,disclaimer_text:null},
  {office_type:'bdo',name_hindi:'पेंशन भुगतान लंबित शिकायत',name_english:'Pension Payment Pending',keywords:JSON.stringify(['पेंशन','pension','लंबित','pending','payment','भुगतान','वृद्धा','विधवा']),required_fields:wb(['pension_type','pension_id','pending_months','bank_account_last4','previous_complaints']),prompt_template:pa('bdo','पेंशन भुगतान लंबित शिकायत','पेंशन प्रकार और ID बताएं।कितने महीने से लंबित है और बैंक का नाम, शाखा और खाते के अंतिम चार अंक बताएं।तत्काल भुगतान का अनुरोध करें।'),requires_legal_disclaimer:0,disclaimer_text:null},
  {office_type:'bdo',name_hindi:'कन्या विवाह सहायता योजना',name_english:'Marriage Assistance Scheme',keywords:JSON.stringify(['कन्या','marriage','विवाह','सहायता']),required_fields:wb(['girl_name','age','education','family_income','marriage_date','bank_account_last4']),prompt_template:pa('bdo','कन्या विवाह सहायता योजना','कन्या का नाम, आयु और शिक्षा बताएं।परिवार आय और विवाह तिथि दें।सहायता राशि स्वीकृत करने का अनुरोध करें।'),requires_legal_disclaimer:0,disclaimer_text:null},
  {office_type:'bdo',name_hindi:'बेरोजगारी भत्ता आवेदन',name_english:'Unemployment Allowance',keywords:JSON.stringify(['बेरोजगारी','unemployment','भत्ता','allowance']),required_fields:wb(['education','age','experience','registration_number','income','bank_account_last4']),prompt_template:pa('bdo','बेरोजगारी भत्ता आवेदन','शैक्षिक योग्यता, आयु और अनुभव बताएं।रोजगार कार्यालय पंजीकरण संख्या दें।पात्रतानुसार भत्ता स्वीकृत करने का अनुरोध करें।'),requires_legal_disclaimer:0,disclaimer_text:null},
  {office_type:'bdo',name_hindi:'मातृत्व सहायता योजना',name_english:'Maternity Assistance',keywords:JSON.stringify(['मातृत्व','maternity','सहायता','गर्भवती']),required_fields:wb(['woman_name','age','husband_name','pregnancy_month','delivery_date','family_income','bank_account_last4']),prompt_template:pa('bdo','मातृत्व सहायता योजना','महिला का नाम, आयु और पति का नाम बताएं।गर्भावस्था महीना और प्रसव तिथि दें।परिवार आय और बैंक का नाम, शाखा और खाते के अंतिम चार अंक बताएं।सहायता राशि का अनुरोध करें।'),requires_legal_disclaimer:0,disclaimer_text:null},
  {office_type:'bdo',name_hindi:'E-Shram कार्ड पंजीकरण',name_english:'E-Shram Card Registration',keywords:JSON.stringify(['E-Shram','labour','श्रम','registration']),required_fields:wb(['worker_name','occupation','age','education','family_members','bank_account_last4']),prompt_template:pa('bdo','E-Shram कार्ड पंजीकरण','श्रमिक का नाम, व्यवसाय, आयु और शिक्षा बताएं।परिवार सदस्य और बैंक का नाम, शाखा और खाते के अंतिम चार अंक बताएं।E-Shram पोर्टल पर पंजीकरण का अनुरोध करें।'),requires_legal_disclaimer:0,disclaimer_text:null},
  {office_type:'bdo',name_hindi:'विकलांगता प्रमाण पत्र आवेदन',name_english:'Disability Certificate',keywords:JSON.stringify(['विकलांगता','disability','certificate','दिव्यांग']),required_fields:wb(['person_name','age','disability_type','disability_percentage','medical_history','purpose']),prompt_template:pa('bdo','विकलांगता प्रमाण पत्र आवेदन','व्यक्ति का नाम, आयु और विकलांगता प्रकार बताएं।प्रमाण पत्र के प्रयोजन का उल्लेख करें।सिविल सर्जन से जाँच कर प्रमाण पत्र का अनुरोध करें।'),requires_legal_disclaimer:0,disclaimer_text:null},
  {office_type:'bdo',name_hindi:'किसान क्रेडिट कार्ड आवेदन',name_english:'Kisan Credit Card Application',keywords:JSON.stringify(['KCC','किसान','credit','कार्ड','क्रेडिट']),required_fields:wb(['farmer_name','land_area','crop_type','annual_income','bank_account_last4','land_documents']),prompt_template:pa('bdo','किसान क्रेडिट कार्ड आवेदन','किसान का नाम, भूमि क्षेत्रफल और फसल प्रकार बताएं।वार्षिक आय और बैंक का नाम, शाखा और खाते के अंतिम चार अंक बताएं।KCC जारी करने का अनुरोध करें।'),requires_legal_disclaimer:0,disclaimer_text:null},

  // SDO (+3) + SP (+2) + DC (+4)
  {office_type:'sdo',name_hindi:'राशन डीलर के विरुद्ध शिकायत',name_english:'Complaint Against Ration Dealer',keywords:JSON.stringify(['डीलर','dealer','ration','शिकायत']),required_fields:wb(['dealer_name','shop_location','ration_card_number','complaint_details','since_when','evidence']),prompt_template:p('sdo','राशन डीलर के विरुद्ध शिकायत','डीलर का नाम और दुकान स्थान बताएं।राशन कार्ड नंबर दें।कब से और कैसी गड़बड़ी है बताएं।जाँच कर कार्रवाई का अनुरोध करें।'),requires_legal_disclaimer:0,disclaimer_text:null},
  {office_type:'sdo',name_hindi:'सरकारी कर्मचारी लापरवाही शिकायत',name_english:'Employee Negligence Complaint',keywords:JSON.stringify(['लापरवाही','negligence','कर्मचारी','सरकारी']),required_fields:wb(['department_name','employee_name','employee_designation','complaint_details','incident_date','impact']),prompt_template:p('sdo','सरकारी कर्मचारी लापरवाही शिकायत','विभाग और कर्मचारी का नाम व पद बताएं।कब और कैसी लापरवाही हुई बताएं।प्रभाव और नुकसान का उल्लेख करें।जाँच कर कार्रवाई का अनुरोध करें।'),requires_legal_disclaimer:0,disclaimer_text:null},
  {office_type:'sdo',name_hindi:'प्रमाण पत्र लंबित शिकायत',name_english:'Certificate Pending Complaint',keywords:JSON.stringify(['प्रमाण पत्र','certificate','pending','लंबित','delay']),required_fields:wb(['certificate_type','application_date','office_name','delay_details','urgency_reason']),prompt_template:pa('sdo','प्रमाण पत्र लंबित शिकायत','किस प्रमाण पत्र हेतु कब और कहाँ आवेदन किया था बताएं।कितने समय से लंबित है और क्यों जरूरी है बताएं।SDO से हस्तक्षेप का अनुरोध करें।'),requires_legal_disclaimer:0,disclaimer_text:null},
  {office_type:'sp',name_hindi:'थाना कार्रवाई न होने की शिकायत',name_english:'Police Inaction Complaint to SP',keywords:JSON.stringify(['कार्रवाई','inaction','police','SP','लंबित']),required_fields:wb(['police_station_name','complaint_date','complaint_subject','officer_name','inaction_details']),prompt_template:p('sp','थाना कार्रवाई न होने की शिकायत','किस थाने में कब शिकायत दी गई बताएं।अधिकारी का नाम और कार्रवाई न होने का विवरण दें।SP से हस्तक्षेप का अनुरोध करें।'),requires_legal_disclaimer:0,disclaimer_text:null},
  {office_type:'sp',name_hindi:'अवैध वसूली की शिकायत',name_english:'Illegal Extortion Complaint',keywords:JSON.stringify(['वसूली','extortion','अवैध','रिश्वत']),required_fields:wb(['incident_date','location','accused_name','accused_father_name','accused_village','extortion_details','amount','evidence']),prompt_template:p('sp','अवैध वसूली की शिकायत','किसने, कब और कितनी राशि की वसूली की बताएं।आरोपी की पहचान और सबूत दें।SP से जाँच कर कार्रवाई का अनुरोध करें।'),requires_legal_disclaimer:0,disclaimer_text:null},
  {office_type:'dc',name_hindi:'जन वितरण प्रणाली शिकायत',name_english:'PDS Complaint',keywords:JSON.stringify(['PDS','ration','distribution','वितरण']),required_fields:wb(['district','block','complaint_details','affected_families','duration']),prompt_template:p('dc','जन वितरण प्रणाली शिकायत','जिले के किस क्षेत्र में PDS/राशन वितरण में समस्या है बताएं।कितने परिवार प्रभावित हैं बताएं।जिलाधिकारी से जाँच कर कार्रवाई का अनुरोध करें।'),requires_legal_disclaimer:0,disclaimer_text:null},
  {office_type:'dc',name_hindi:'विभागीय भ्रष्टाचार शिकायत',name_english:'Departmental Corruption Complaint',keywords:JSON.stringify(['भ्रष्टाचार','corruption','विभाग','रिश्वत']),required_fields:wb(['department_name','employee_name','employee_designation','incident_details','amount_involved','evidence','witnesses']),prompt_template:p('dc','विभागीय भ्रष्टाचार शिकायत','किस विभाग के कर्मचारी द्वारा भ्रष्टाचार किया गया बताएं।राशि, सबूत और गवाहों का उल्लेख करें।जिलाधिकारी से जाँच कर कार्रवाई का अनुरोध करें।'),requires_legal_disclaimer:0,disclaimer_text:null},
  {office_type:'dc',name_hindi:'सरकारी योजना से वंचित शिकायत',name_english:'Scheme Exclusion Complaint',keywords:JSON.stringify(['योजना','scheme','exclusion','वंचित']),required_fields:wb(['scheme_name','eligibility_details','denial_reason','application_date','previous_complaints']),prompt_template:p('dc','सरकारी योजना से वंचित शिकायत','किस योजना का लाभ नहीं मिल रहा और पात्रता विवरण दें।कब आवेदन किया और क्यों मना हुआ बताएं।जिलाधिकारी से हस्तक्षेप का अनुरोध करें।'),requires_legal_disclaimer:0,disclaimer_text:null},
  {office_type:'dc',name_hindi:'लोक शिकायत निवारण आवेदन',name_english:'Public Grievance Redressal Request',keywords:JSON.stringify(['लोक','public','grievance','शिकायत','निवारण']),required_fields:wb(['department_name','grievance_category','grievance_details','affected_parties','prior_escalation']),prompt_template:p('dc','लोक शिकायत निवारण आवेदन','शिकायत श्रेणी और विभाग बताएं।समस्या का विस्तृत विवरण दें।अब तक के शिकायत स्तर और परिणाम बताएं।जिलाधिकारी से समाधान का अनुरोध करें।'),requires_legal_disclaimer:0,disclaimer_text:null},

  // COURT (+5)
  {office_type:'court',name_hindi:'शपथ पत्र — सामान्य प्रयोजन',name_english:'Affidavit — General Purpose',keywords:JSON.stringify(['शपथ पत्र','affidavit','general','हलफनामा']),required_fields:wb(['deponent_name','deponent_father_name','deponent_age','deponent_address','purpose','statement_of_facts','court_name']),prompt_template:p('court','शपथ पत्र — सामान्य प्रयोजन','शपथकर्ता का नाम, पिता का नाम, आयु और पता दें।प्रयोजन और तथ्यों का क्रमांकित विवरण दें।न्यायालय का नाम और हस्ताक्षर स्थान छोड़ें।'),requires_legal_disclaimer:1,disclaimer_text:COURT_DISCLAIMER},
  {office_type:'court',name_hindi:'प्रमाणित प्रति आवेदन',name_english:'Certified Copy Application',keywords:JSON.stringify(['प्रमाणित','certified','copy','प्रति']),required_fields:wb(['case_number','case_type','court_name','document_type','purpose']),prompt_template:pa('court','प्रमाणित प्रति आवेदन','केस नंबर, प्रकार और न्यायालय बताएं।किस दस्तावेज़ की प्रमाणित प्रति चाहिए और प्रयोजन बताएं।प्रमाणित प्रति निर्गत करने का अनुरोध करें।'),requires_legal_disclaimer:1,disclaimer_text:COURT_DISCLAIMER},
  {office_type:'court',name_hindi:'तिथि विस्तार आवेदन',name_english:'Date Extension Application',keywords:JSON.stringify(['तिथि','date','extension','विस्तार']),required_fields:wb(['case_number','case_type','court_name','extension_reason','requested_extension_period']),prompt_template:pa('court','तिथि विस्तार आवेदन','केस नंबर और न्यायालय बताएं।विस्तार का कारण और कितना समय चाहिए बताएं।तिथि विस्तार स्वीकृत करने का अनुरोध करें।'),requires_legal_disclaimer:1,disclaimer_text:COURT_DISCLAIMER},
  {office_type:'court',name_hindi:'कानूनी नोटिस प्रारूप',name_english:'Legal Notice Format',keywords:JSON.stringify(['legal','notice','कानूनी','नोटिस','वकील']),required_fields:wb(['sender_name','sender_address','recipient_name','recipient_address','subject','facts','relief_claimed','deadline_days']),prompt_template:p('court','कानूनी नोटिस प्रारूप','प्रेषक और प्राप्तकर्ता का नाम व पता दें।नोटिस का विषय और तथ्य क्रमबद्ध रूप में दें।माँगी गई राहत और समय-सीमा बताएं।'),requires_legal_disclaimer:1,disclaimer_text:COURT_DISCLAIMER},
  {office_type:'court',name_hindi:'रख-रखाव आवेदन प्रारूप',name_english:'Maintenance Application',keywords:JSON.stringify(['maintenance','रख-रखाव','भरण-पोषण','family']),required_fields:wb(['applicant_name','respondent_name','respondent_father_name','respondent_village','relationship','marriage_date','income_details','maintenance_amount']),prompt_template:p('court','रख-रखाव आवेदन प्रारूप','आवेदक और प्रत्यर्थी का नाम व संबंध बताएं।विवाह तिथि और प्रत्यर्थी की आय दें।रख-रखाव राशि का औचित्य और माँग बताएं।'),requires_legal_disclaimer:1,disclaimer_text:COURT_DISCLAIMER},

  // BANK (+8)
  {office_type:'bank',name_hindi:'नया बैंक खाता खोलने हेतु आवेदन',name_english:'New Bank Account',keywords:JSON.stringify(['नया','new','account','खाता']),required_fields:wb(['bank_name','branch','account_type','nominee_name','nominee_relation','initial_deposit']),prompt_template:pa('bank','नया बैंक खाता खोलने हेतु आवेदन','बैंक और शाखा का नाम बताएं।खाता प्रकार और नामांकित व्यक्ति का नाम व संबंध बताएं।नया खाता खोलने का अनुरोध करें।'),requires_legal_disclaimer:0,disclaimer_text:null},
  {office_type:'bank',name_hindi:'नामांकन बदलने हेतु आवेदन',name_english:'Nominee Change',keywords:JSON.stringify(['nominee','नामांकन','change']),required_fields:wb(['bank_name','branch','account_number_last4','old_nominee','new_nominee','new_nominee_relation','reason']),prompt_template:pa('bank','नामांकन बदलने हेतु आवेदन','बैंक, शाखा और खाते के अंतिम 4 अंक बताएं।पुराने और नए नामांकित व्यक्ति का नाम व संबंध बताएं।नामांकन परिवर्तन का अनुरोध करें।'),requires_legal_disclaimer:0,disclaimer_text:null},
  {office_type:'bank',name_hindi:'ATM कार्ड ब्लॉक करने हेतु आवेदन',name_english:'ATM Card Block Request',keywords:JSON.stringify(['ATM','block','कार्ड','खोना']),required_fields:wb(['bank_name','branch','account_number_last4','card_type','loss_reason','loss_date']),prompt_template:pa('bank','ATM कार्ड ब्लॉक करने हेतु आवेदन','बैंक, शाखा और खाते के अंतिम 4 अंक बताएं।खोने/चोरी की तिथि और परिस्थिति बताएं।तत्काल कार्ड ब्लॉक कर नया कार्ड जारी करने का अनुरोध करें।'),requires_legal_disclaimer:0,disclaimer_text:null},
  {office_type:'bank',name_hindi:'गलत डेबिट की शिकायत',name_english:'Wrong Debit Complaint',keywords:JSON.stringify(['debit','गलत','wrong','transaction']),required_fields:wb(['bank_name','branch','account_number_last4','transaction_date','transaction_amount','transaction_id']),prompt_template:pa('bank','गलत डेबिट की शिकायत','बैंक, शाखा और खाते के अंतिम 4 अंक बताएं।गलत कटौती की तारीख, राशि और ट्रांजेक्शन ID दें।जाँच कर राशि वापसी का अनुरोध करें।'),requires_legal_disclaimer:0,disclaimer_text:null},
  {office_type:'bank',name_hindi:'ATM राशि न निकलने की शिकायत',name_english:'ATM Cash Not Dispensed',keywords:JSON.stringify(['ATM','cash','not dispensed','amount']),required_fields:wb(['bank_name','atm_location','transaction_date','transaction_amount','transaction_id','account_number_last4']),prompt_template:pa('bank','ATM राशि न निकलने की शिकायत','बैंक, ATM स्थान और लेन-देन तारीख बताएं।खाते से कटी राशि और ट्रांजेक्शन ID दें।जाँच कर राशि वापसी का अनुरोध करें।'),requires_legal_disclaimer:0,disclaimer_text:null},
  {office_type:'bank',name_hindi:'लोन स्टेटमेंट अनुरोध',name_english:'Loan Statement Request',keywords:JSON.stringify(['लोन','loan','statement','स्टेटमेंट','बैंक','bank','विवरण']),required_fields:wb(['bank_name','branch','loan_account_number','statement_period','purpose']),prompt_template:pa('bank','लोन स्टेटमेंट अनुरोध','बैंक, शाखा और लोन खाता संख्या बताएं।किस अवधि का स्टेटमेंट और प्रयोजन बताएं।लोन स्टेटमेंट निर्गत करने का अनुरोध करें।'),requires_legal_disclaimer:0,disclaimer_text:null},
  {office_type:'bank',name_hindi:'अनधिकृत लेन-देन की शिकायत',name_english:'Unauthorized Transaction',keywords:JSON.stringify(['unauthorized','अनधिकृत','transaction','fraud']),required_fields:wb(['bank_name','branch','account_number_last4','transaction_date','transaction_amount','transaction_id']),prompt_template:p('bank','अनधिकृत लेन-देन की शिकायत','बैंक और खाते के अंतिम 4 अंक बताएं।अनधिकृत लेन-देन की तारीख, राशि और ID दें।जाँच कर राशि वापसी का अनुरोध करें।'),requires_legal_disclaimer:0,disclaimer_text:null},
  {office_type:'bank',name_hindi:'मृतक खाताधारक दावा आवेदन',name_english:'Deceased Account Claim',keywords:JSON.stringify(['मृतक','deceased','claim','दावा']),required_fields:wb(['bank_name','branch','deceased_name','account_number_last4','relation_to_deceased','death_date','nominee_status']),prompt_template:pa('bank','मृतक खाताधारक दावा आवेदन','बैंक, शाखा और मृतक का नाम व खाता अंतिम अंक बताएं।आवेदक का संबंध और मृत्यु तिथि दें।मृत्यु प्रमाण पत्र संलग्न कर खाता राशि भुगतान का अनुरोध करें।'),requires_legal_disclaimer:0,disclaimer_text:null},

  // COLLEGE (+3) + SCHOOL (+5)
  {office_type:'college',name_hindi:'माइग्रेशन प्रमाण पत्र आवेदन',name_english:'Migration Certificate',keywords:JSON.stringify(['migration','माइग्रेशन','transfer']),required_fields:wb(['college_name','course_name','roll_number','new_institution','academic_year','transfer_reason']),prompt_template:pa('college','माइग्रेशन प्रमाण पत्र आवेदन','महाविद्यालय, पाठ्यक्रम और रोल नंबर बताएं।नए संस्थान और स्थानांतरण कारण बताएं।माइग्रेशन प्रमाण पत्र जारी करने का अनुरोध करें।'),requires_legal_disclaimer:0,disclaimer_text:null},
  {office_type:'college',name_hindi:'छात्रवृत्ति भुगतान शिकायत',name_english:'Scholarship Payment Complaint',keywords:JSON.stringify(['छात्रवृत्ति','scholarship','payment','शिकायत']),required_fields:wb(['college_name','course_name','roll_number','scholarship_name','application_id','pending_since','bank_account_last4']),prompt_template:pa('college','छात्रवृत्ति भुगतान शिकायत','महाविद्यालय, पाठ्यक्रम और रोल नंबर बताएं।किस छात्रवृत्ति का भुगतान लंबित है बताएं।कब से और बैंक का नाम, शाखा और खाते के अंतिम चार अंक बताएं।भुगतान जाँच का अनुरोध करें।'),requires_legal_disclaimer:0,disclaimer_text:null},
  {office_type:'college',name_hindi:'पुस्तकालय कार्ड आवेदन',name_english:'Library Card Application',keywords:JSON.stringify(['library','पुस्तकालय','card']),required_fields:wb(['college_name','course_name','roll_number','academic_year','address']),prompt_template:pa('college','पुस्तकालय कार्ड आवेदन','महाविद्यालय, पाठ्यक्रम और रोल नंबर बताएं।पुस्तकालय कार्ड निर्गत करने का अनुरोध करें।'),requires_legal_disclaimer:0,disclaimer_text:null},
  {office_type:'school',name_hindi:'प्रवेश आवेदन',name_english:'School Admission Application',keywords:JSON.stringify(['प्रवेश','admission','new','दाखिला']),required_fields:wb(['school_name','class_name','child_name','dob','father_name','mother_name','previous_school','address']),prompt_template:pa('school','प्रवेश आवेदन','विद्यालय और कक्षा बताएं।बच्चे का नाम, जन्म तिथि और माता-पिता का नाम दें।पिछला विद्यालय और पता बताएं।प्रवेश प्रदान करने का अनुरोध करें।'),requires_legal_disclaimer:0,disclaimer_text:null},
  {office_type:'school',name_hindi:'मार्कशीट सुधार आवेदन',name_english:'Marksheet Correction',keywords:JSON.stringify(['marksheet','correction','सुधार','अंकसूची']),required_fields:wb(['school_name','class_name','roll_number','exam_year','correction_type','current_info','correct_info']),prompt_template:pa('school','मार्कशीट सुधार आवेदन','विद्यालय, कक्षा, रोल नंबर और परीक्षा वर्ष बताएं।क्या सुधार चाहिए और गलत/सही जानकारी दें।मार्कशीट में सुधार का अनुरोध करें।'),requires_legal_disclaimer:0,disclaimer_text:null},
  {office_type:'school',name_hindi:'जन्म तिथि सुधार आवेदन',name_english:'DOB Correction',keywords:JSON.stringify(['DOB','जन्म तिथि','correction']),required_fields:wb(['school_name','class_name','roll_number','current_dob','correct_dob','supporting_documents']),prompt_template:pa('school','जन्म तिथि सुधार आवेदन','विद्यालय, कक्षा और रोल नंबर बताएं।वर्तमान और सही जन्म तिथि दें।प्रमाण दस्तावेज़ संलग्न कर सुधार का अनुरोध करें।'),requires_legal_disclaimer:0,disclaimer_text:null},
  {office_type:'school',name_hindi:'परीक्षा फॉर्म सुधार आवेदन',name_english:'Exam Form Correction',keywords:JSON.stringify(['परीक्षा','exam','form','correction']),required_fields:wb(['school_name','class_name','roll_number','exam_name','correction_details','current_info','correct_info']),prompt_template:pa('school','परीक्षा फॉर्म सुधार आवेदन','विद्यालय, कक्षा, रोल नंबर और परीक्षा नाम बताएं।फॉर्म में सुधार विवरण दें।परीक्षा फॉर्म सुधार का अनुरोध करें।'),requires_legal_disclaimer:0,disclaimer_text:null},
  {office_type:'school',name_hindi:'मिड-डे मील शिकायत',name_english:'Mid-Day Meal Complaint',keywords:JSON.stringify(['मिड-डे मील','MDM','food','शिकायत']),required_fields:wb(['school_name','complaint_details','incident_date','affected_students','complaint_type','witnesses']),prompt_template:p('school','मिड-डे मील शिकायत','विद्यालय का नाम और शिकायत विवरण दें।कितने बच्चे प्रभावित हुए और कब बताएं।गवाहों का उल्लेख करें।जाँच कर सुधार का अनुरोध करें।'),requires_legal_disclaimer:0,disclaimer_text:null},

  // PWD (+5) + RCD (+3)
  {office_type:'pwd',name_hindi:'नया बिजली कनेक्शन आवेदन',name_english:'New Electricity Connection',keywords:JSON.stringify(['बिजली','electricity','connection','नया']),required_fields:wb(['address','load_required','purpose','nearby_pole']),prompt_template:pa('pwd','नया बिजली कनेक्शन आवेदन','पता और कितना लोड चाहिए बताएं।प्रयोजन बताएं।नया कनेक्शन प्रदान करने का अनुरोध करें।'),requires_legal_disclaimer:0,disclaimer_text:null},
  {office_type:'pwd',name_hindi:'बिजली मीटर बदलने हेतु आवेदन',name_english:'Meter Replacement',keywords:JSON.stringify(['बिजली','electricity','मीटर','meter','बदलना','replacement','बिल','bill']),required_fields:wb(['consumer_number','address','meter_problem','since_when']),prompt_template:pa('pwd','बिजली मीटर बदलने हेतु आवेदन','उपभोक्ता संख्या और पता बताएं।मीटर में क्या समस्या है और कब से है बताएं।मीटर बदलने का अनुरोध करें।'),requires_legal_disclaimer:0,disclaimer_text:null},
  {office_type:'pwd',name_hindi:'गलत बिजली बिल की शिकायत',name_english:'Incorrect Electricity Bill',keywords:JSON.stringify(['बिजली','electricity','बिल','bill','गलत','high','अधिक','शिकायत']),required_fields:wb(['consumer_number','bill_number','bill_amount','expected_amount','billing_period','meter_reading']),prompt_template:pa('pwd','गलत बिजली बिल की शिकायत','उपभोक्ता संख्या, बिल नंबर और बिलिंग अवधि बताएं।बिल राशि और अपेक्षित राशि दें।मीटर रीडिंग दें।बिल सुधार का अनुरोध करें।'),requires_legal_disclaimer:0,disclaimer_text:null},
  {office_type:'pwd',name_hindi:'ट्रांसफार्मर खराब शिकायत',name_english:'Transformer Failure Complaint',keywords:JSON.stringify(['ट्रांसफार्मर','transformer','खराब','बिजली']),required_fields:wb(['location','transformer_location','problem_description','since_when','affected_area']),prompt_template:p('pwd','ट्रांसफार्मर खराब शिकायत','ट्रांसफार्मर स्थान और खराबी विवरण दें।कब से और कितने घर प्रभावित हैं बताएं।तत्काल मरम्मत का अनुरोध करें।'),requires_legal_disclaimer:0,disclaimer_text:null},
  {office_type:'pwd',name_hindi:'बिजली चोरी की शिकायत',name_english:'Electricity Theft Complaint',keywords:JSON.stringify(['बिजली','electricity','चोरी','theft','अवैध','कटिया','तार']),required_fields:wb(['location','accused_name','accused_father_name','accused_village','theft_details','since_when']),prompt_template:p('pwd','बिजली चोरी की शिकायत','कहाँ और किसके द्वारा बिजली चोरी हो रही है बताएं।आरोपी की पहचान दें।कब से और कैसे हो रही है बताएं।कार्रवाई का अनुरोध करें।'),requires_legal_disclaimer:0,disclaimer_text:null},
  {office_type:'rcd',name_hindi:'हैंडपंप मरम्मत आवेदन',name_english:'Handpump Repair',keywords:JSON.stringify(['हैंडपंप','handpump','repair','पानी']),required_fields:wb(['village','handpump_location','problem_description','since_when','affected_families']),prompt_template:pa('rcd','हैंडपंप मरम्मत आवेदन','गाँव और हैंडपंप स्थान बताएं।क्या खराबी है और कब से है बताएं।कितने परिवार प्रभावित हैं बताएं।तत्काल मरम्मत का अनुरोध करें।'),requires_legal_disclaimer:0,disclaimer_text:null},
  {office_type:'rcd',name_hindi:'नाली निर्माण आवेदन',name_english:'Drain Construction',keywords:JSON.stringify(['नाली','drain','निर्माण','जल निकासी']),required_fields:wb(['village','location','current_situation','proposed_length','beneficiary_families']),prompt_template:pa('rcd','नाली निर्माण आवेदन','गाँव और स्थान बताएं।वर्तमान जल निकासी स्थिति और आवश्यकता बताएं।प्रस्तावित लंबाई और लाभार्थी परिवार बताएं।नाली निर्माण स्वीकृत करने का अनुरोध करें।'),requires_legal_disclaimer:0,disclaimer_text:null},
  {office_type:'rcd',name_hindi:'स्ट्रीट लाइट मरम्मत आवेदन',name_english:'Street Light Repair',keywords:JSON.stringify(['स्ट्रीट लाइट','street light','repair']),required_fields:wb(['village','light_location','problem_description','since_when','affected_area']),prompt_template:pa('rcd','स्ट्रीट लाइट मरम्मत आवेदन','गाँव और लाइट स्थान बताएं।क्या खराबी है और कब से है बताएं।प्रभावित क्षेत्र बताएं।तत्काल मरम्मत का अनुरोध करें।'),requires_legal_disclaimer:0,disclaimer_text:null},
  // Batch 2 (+35 more to reach 200+)
  {office_type:'thana',name_hindi:'महिला प्रताड़ना — ससुराल पक्ष द्वारा प्रताड़ना',name_english:'Women Harassment by In-Laws',keywords:JSON.stringify(['महिला','women','प्रताड़ना','harassment','ससुराल','in-laws']),required_fields:wb(['incident_date','accused_names','accused_father_name','accused_village','marriage_date','incident_details','witnesses']),prompt_template:p('thana','ससुराल पक्ष द्वारा प्रताड़ना','विवाह तिथि और ससुराल पक्ष के आरोपियों का नाम बताएं।कब से और कैसे प्रताड़ना हो रही है बताएं।गवाहों का उल्लेख करें।घरेलू हिंसा अधिनियम के तहत कार्रवाई का अनुरोध करें।'),requires_legal_disclaimer:0,disclaimer_text:null},
  {office_type:'thana',name_hindi:'बुजुर्ग माता-पिता से मारपीट',name_english:'Elderly Parents Assault Complaint',keywords:JSON.stringify(['बुजुर्ग','elderly','parents','मारपीट','senior']),required_fields:wb(['victim_name','victim_age','accused_name','accused_father_name','accused_village','relationship','incident_details','witnesses']),prompt_template:p('thana','बुजुर्ग माता-पिता से मारपीट','पीड़ित बुजुर्ग का नाम और आयु बताएं।आरोपी का नाम और पीड़ित से संबंध बताएं।मारपीट का विवरण दें।वरिष्ठ नागरिक अधिनियम के तहत कार्रवाई का अनुरोध करें।'),requires_legal_disclaimer:0,disclaimer_text:null},
  {office_type:'thana',name_hindi:'जान से मारने की धमकी',name_english:'Death Threat Complaint',keywords:JSON.stringify(['धमकी','death threat','जान','kill']),required_fields:wb(['incident_date','incident_time','location','accused_name','accused_father_name','accused_village','threat_details','evidence','witnesses','prior_incidents']),prompt_template:p('thana','जान से मारने की धमकी','आरोपी ने कब, कहाँ और किन शब्दों में जान से मारने की धमकी दी बताएं।आरोपी की पूरी पहचान दें।सबूत और पूर्व घटनाओं का उल्लेख करें।प्राथमिकी और सुरक्षा का अनुरोध करें।'),requires_legal_disclaimer:0,disclaimer_text:null},
  {office_type:'co',name_hindi:'भू-राजस्व बकाया भुगतान आवेदन',name_english:'Land Revenue Payment',keywords:JSON.stringify(['राजस्व','revenue','payment','बकाया']),required_fields:wb(['khata_number','khasra_number','mouja_name','pending_amount','pending_years','payment_mode']),prompt_template:pa('co','भू-राजस्व बकाया भुगतान आवेदन','खसरा/खाता और मौजा बताएं।कितने वर्षों का कितना राजस्व बकाया है बताएं।बकाया जमा कर रसीद प्राप्त करने का अनुरोध करें।'),requires_legal_disclaimer:0,disclaimer_text:null},
  {office_type:'co',name_hindi:'भूमि बंटवारा आवेदन',name_english:'Land Partition Application',keywords:JSON.stringify(['बंटवारा','partition','division','भूमि']),required_fields:wb(['khata_number','khasra_number','mouja_name','co_owners','share_ratio','partition_reason','family_tree']),prompt_template:pa('co','भूमि बंटवारा आवेदन','खसरा/खाता और मौजा बताएं।सह-स्वामियों का नाम और हिस्सा अनुपात बताएं।बंटवारे का कारण और वंशावली दें।राजस्व अधिकारी से बंटवारा कराने का अनुरोध करें।'),requires_legal_disclaimer:0,disclaimer_text:null},
  {office_type:'block',name_hindi:'मृत्यु प्रमाण पत्र सुधार आवेदन',name_english:'Death Certificate Correction',keywords:JSON.stringify(['मृत्यु','death','certificate','correction','सुधार']),required_fields:wb(['death_certificate_number','registration_date','deceased_name','correction_type','current_info','correct_info','reason']),prompt_template:pa('block','मृत्यु प्रमाण पत्र सुधार आवेदन','मृत्यु प्रमाण पत्र संख्या और पंजीकरण तिथि बताएं।मृतक का नाम और सुधार विवरण दें।गलत और सही जानकारी बताएं।प्रमाण पत्र में सुधार का अनुरोध करें।'),requires_legal_disclaimer:0,disclaimer_text:null},
  {office_type:'block',name_hindi:'गंदे पानी की शिकायत',name_english:'Contaminated Water Complaint',keywords:JSON.stringify(['गंदा','dirty','water','contaminated','स्वास्थ्य']),required_fields:wb(['location','water_source','problem_description','since_when','affected_families','health_impact']),prompt_template:p('block','गंदे पानी की शिकायत','किस क्षेत्र में गंदा पानी आ रहा है और स्रोत बताएं।कब से समस्या है और कितने परिवार प्रभावित हैं बताएं।स्वास्थ्य प्रभाव बताएं।शुद्ध पेयजल आपूर्ति का अनुरोध करें।'),requires_legal_disclaimer:0,disclaimer_text:null},
  {office_type:'block',name_hindi:'पाइप लाइन लीकेज शिकायत',name_english:'Water Pipeline Leakage Complaint',keywords:JSON.stringify(['पाइप','pipe','leakage','पानी','बर्बादी']),required_fields:wb(['location','leakage_description','since_when','water_wastage','affected_area']),prompt_template:p('block','पाइप लाइन लीकेज शिकायत','कहाँ लीकेज है और कब से है बताएं।लीकेज का विवरण और पानी बर्बादी का अनुमान दें।प्रभावित क्षेत्र बताएं।तत्काल मरम्मत का अनुरोध करें।'),requires_legal_disclaimer:0,disclaimer_text:null},
  {office_type:'sdo',name_hindi:'विद्युत विभाग शिकायत',name_english:'Electricity Department Complaint',keywords:JSON.stringify(['बिजली','electricity','शिकायत','विभाग']),required_fields:wb(['department_name','consumer_number','complaint_details','since_when','previous_complaints','impact']),prompt_template:p('sdo','विद्युत विभाग शिकायत','उपभोक्ता संख्या और शिकायत विवरण दें।कब से समस्या है और पूर्व शिकायतों का उल्लेख करें।SDO से जाँच कर समाधान का अनुरोध करें।'),requires_legal_disclaimer:0,disclaimer_text:null},
  {office_type:'sdo',name_hindi:'सार्वजनिक रास्ता खुलवाने का अनुरोध',name_english:'Public Road Reopening Request',keywords:JSON.stringify(['रास्ता','road','public','सार्वजनिक']),required_fields:wb(['location','route_description','obstruction_details','since_when','affected_people','previous_complaints']),prompt_template:p('sdo','सार्वजनिक रास्ता खुलवाने का अनुरोध','किस स्थान पर सार्वजनिक रास्ता बंद है और कब से है बताएं।कितने लोग प्रभावित हैं बताएं।SDO से निरीक्षण कर रास्ता खुलवाने का अनुरोध करें।'),requires_legal_disclaimer:0,disclaimer_text:null},
  {office_type:'dc',name_hindi:'भूमि रिकॉर्ड RTI आवेदन',name_english:'Land Record RTI',keywords:JSON.stringify(['RTI','land','भूमि','record','रिकॉर्ड']),required_fields:wb(['department_name','information_requested','plot_details','time_period','format_required','ipo_details']),prompt_template:pa('dc','भूमि रिकॉर्ड RTI आवेदन','RTI Act 2005 की धारा 6 के अंतर्गत आवेदन।किस विभाग से, किस भूमि की जानकारी चाहिए बताएं।किस अवधि और प्रारूप में चाहिए बताएं।IPO विवरण दें।'),requires_legal_disclaimer:0,disclaimer_text:null},
  {office_type:'dc',name_hindi:'राशन वितरण RTI आवेदन',name_english:'PDS Distribution RTI',keywords:JSON.stringify(['RTI','ration','PDS','distribution']),required_fields:wb(['department_name','information_requested','shop_location','time_period','format_required','ipo_details']),prompt_template:pa('dc','राशन वितरण RTI आवेदन','RTI Act 2005 के तहत आवेदन।किस राशन दुकान की वितरण जानकारी चाहिए बताएं।समय-सीमा और प्रारूप बताएं।IPO विवरण दें।'),requires_legal_disclaimer:0,disclaimer_text:null},
  {office_type:'dc',name_hindi:'मनरेगा भुगतान RTI आवेदन',name_english:'MGNREGA Payment RTI',keywords:JSON.stringify(['RTI','NREGA','payment','मनरेगा']),required_fields:wb(['department_name','information_requested','village_panchayat','time_period','format_required','ipo_details']),prompt_template:pa('dc','मनरेगा भुगतान RTI आवेदन','RTI Act 2005 के तहत आवेदन।किस ग्राम पंचायत की मनरेगा भुगतान जानकारी चाहिए बताएं।IPO विवरण दें।'),requires_legal_disclaimer:0,disclaimer_text:null},
  {office_type:'court',name_hindi:'उपभोक्ता शिकायत प्रारूप',name_english:'Consumer Complaint Format',keywords:JSON.stringify(['consumer','उपभोक्ता','complaint','product']),required_fields:wb(['complainant_name','complainant_address','product_service_details','purchase_date','defect_description','relief_sought','opposite_party_name','opposite_party_address']),prompt_template:p('court','उपभोक्ता शिकायत प्रारूप','उपभोक्ता संरक्षण अधिनियम के तहत शिकायत प्रारूप।शिकायतकर्ता का नाम-पता और उत्पाद/सेवा विवरण दें।दोष और माँगी गई राहत बताएं।विपक्षी का नाम-पता दें।'),requires_legal_disclaimer:1,disclaimer_text:COURT_DISCLAIMER},
  {office_type:'court',name_hindi:'अंडरटेकिंग/वचनबद्धता पत्र',name_english:'Undertaking Letter',keywords:JSON.stringify(['undertaking','वचनबद्धता','declaration']),required_fields:wb(['declarant_name','declarant_father_name','declarant_address','purpose','declaration_details','witnesses','court_name']),prompt_template:pa('court','अंडरटेकिंग/वचनबद्धता पत्र','घोषणाकर्ता का नाम, पिता का नाम और पता दें।किस विषय में वचनबद्धता देनी है और शर्तें बताएं।गवाह और न्यायालय का नाम दें।'),requires_legal_disclaimer:1,disclaimer_text:COURT_DISCLAIMER},
  {office_type:'bank',name_hindi:'डीबीटी भुगतान लंबित शिकायत',name_english:'DBT Payment Pending',keywords:JSON.stringify(['DBT','direct benefit','payment','लंबित']),required_fields:wb(['bank_name','branch','account_number_last4','scheme_name','pending_amount','pending_since','aadhar_last4']),prompt_template:pa('bank','डीबीटी भुगतान लंबित शिकायत','बैंक, शाखा और खाते के अंतिम 4 अंक बताएं।किस योजना का DBT भुगतान लंबित है बताएं।राशि और कब से लंबित है बताएं।भुगतान जाँच का अनुरोध करें।'),requires_legal_disclaimer:0,disclaimer_text:null},
  {office_type:'bank',name_hindi:'लोन बंद करने हेतु आवेदन',name_english:'Loan Closure Application',keywords:JSON.stringify(['लोन','loan','closure','बंद','close','repayment','बैंक','bank']),required_fields:wb(['bank_name','branch','loan_account_number','outstanding_amount','repayment_date','noc_required']),prompt_template:pa('bank','लोन बंद करने हेतु आवेदन','बैंक, शाखा और लोन खाता संख्या बताएं।बकाया राशि और चुकौती तिथि बताएं।खाता बंद कर NOC निर्गत करने का अनुरोध करें।'),requires_legal_disclaimer:0,disclaimer_text:null},
  {office_type:'college',name_hindi:'इंटर्नशिप अनुमति आवेदन',name_english:'Internship Permission',keywords:JSON.stringify(['internship','इंटर्नशिप','permission','training']),required_fields:wb(['college_name','course_name','roll_number','internship_organization','duration','start_date','supervisor_name']),prompt_template:pa('college','इंटर्नशिप अनुमति आवेदन','महाविद्यालय, पाठ्यक्रम और रोल नंबर बताएं।इंटर्नशिप संस्थान, अवधि और तिथि बताएं।प्राचार्य से अनुमति का अनुरोध करें।'),requires_legal_disclaimer:0,disclaimer_text:null},
  {office_type:'school',name_hindi:'मेडिकल अवकाश आवेदन',name_english:'Medical Leave Application',keywords:JSON.stringify(['medical','मेडिकल','leave','अवकाश','बीमार']),required_fields:wb(['school_name','class_name','roll_number','illness_details','leave_dates','doctor_advised_rest','expected_return_date']),prompt_template:pa('school','मेडिकल अवकाश आवेदन','विद्यालय, कक्षा और रोल नंबर बताएं।बीमारी विवरण और डॉक्टर का आराम सुझाव बताएं।अवकाश तिथियाँ और वापसी तिथि बताएं।मेडिकल प्रमाण पत्र संलग्न कर अवकाश स्वीकृत करने का अनुरोध करें।'),requires_legal_disclaimer:0,disclaimer_text:null},
  {office_type:'pwd',name_hindi:'बिजली नाम परिवर्तन आवेदन',name_english:'Electricity Name Change',keywords:JSON.stringify(['नाम','name','change','बिजली','transfer']),required_fields:wb(['consumer_number','old_name','new_name','change_reason','address']),prompt_template:pa('pwd','बिजली नाम परिवर्तन आवेदन','उपभोक्ता संख्या और पुराना/नया नाम बताएं।नाम परिवर्तन का कारण बताएं।बिजली बिल में नाम परिवर्तन का अनुरोध करें।'),requires_legal_disclaimer:0,disclaimer_text:null},
  {office_type:'pwd',name_hindi:'लोड बढ़ाने हेतु आवेदन',name_english:'Electricity Load Increase',keywords:JSON.stringify(['लोड','load','increase','capacity']),required_fields:wb(['consumer_number','current_load','requested_load','reason','address']),prompt_template:pa('pwd','लोड बढ़ाने हेतु आवेदन','उपभोक्ता संख्या और वर्तमान/अनुरोधित लोड बताएं।लोड बढ़ाने का कारण बताएं।नियमानुसार लोड वृद्धि स्वीकृत करने का अनुरोध करें।'),requires_legal_disclaimer:0,disclaimer_text:null},
  {office_type:'pwd',name_hindi:'बिजली कनेक्शन काटने की शिकायत',name_english:'Electricity Disconnection Complaint',keywords:JSON.stringify(['कनेक्शन','disconnection','काटना','बिजली']),required_fields:wb(['consumer_number','disconnection_date','bill_details','payment_proof','grievance_details']),prompt_template:p('pwd','बिजली कनेक्शन काटने की शिकायत','उपभोक्ता संख्या और कनेक्शन काटने की तिथि बताएं।बिल विवरण और भुगतान प्रमाण दें।जाँच कर कनेक्शन बहाल करने का अनुरोध करें।'),requires_legal_disclaimer:0,disclaimer_text:null},
  {office_type:'bdo',name_hindi:'ग्राम सभा सदस्यता आवेदन',name_english:'Gram Sabha Membership',keywords:JSON.stringify(['ग्राम सभा','gram sabha','membership']),required_fields:wb(['village_name','panchayat_name','residence_duration','age']),prompt_template:pa('bdo','ग्राम सभा सदस्यता आवेदन','गाँव और पंचायत का नाम बताएं।कितने समय से निवास कर रहे हैं और आयु बताएं।ग्राम सभा सदस्यता में नाम जोड़ने का अनुरोध करें।'),requires_legal_disclaimer:0,disclaimer_text:null},
  {office_type:'rcd',name_hindi:'चापाकल मरम्मत आवेदन',name_english:'Hand Pump Repair',keywords:JSON.stringify(['चापाकल','hand pump','repair','पानी']),required_fields:wb(['village','pump_location','problem_description','since_when','affected_families']),prompt_template:pa('rcd','चापाकल मरम्मत आवेदन','गाँव और चापाकल स्थान बताएं।खराबी विवरण और कब से है बताएं।कितने परिवार प्रभावित हैं बताएं।तत्काल मरम्मत का अनुरोध करें।'),requires_legal_disclaimer:0,disclaimer_text:null},
  {office_type:'bcd',name_hindi:'सरकारी भवन जीर्णोद्धार आवेदन',name_english:'Govt Building Renovation',keywords:JSON.stringify(['जीर्णोद्धार','renovation','building','भवन']),required_fields:wb(['building_name','location','building_age','damage_details','estimated_cost','urgency']),prompt_template:pa('bcd','सरकारी भवन जीर्णोद्धार आवेदन','भवन का नाम, स्थान और उम्र बताएं।क्षति विवरण और अनुमानित लागत दें।जीर्णोद्धार की तत्काल आवश्यकता बताएं।निरीक्षण कर कार्य स्वीकृत करने का अनुरोध करें।'),requires_legal_disclaimer:0,disclaimer_text:null},
  {office_type:'sp',name_hindi:'साइबर अपराध एस्कलेशन',name_english:'Cyber Crime Escalation to SP',keywords:JSON.stringify(['साइबर','cyber','escalation','SP']),required_fields:wb(['police_station_name','complaint_date','fir_number','incident_details','investigation_status','escalation_reason']),prompt_template:p('sp','साइबर अपराध एस्कलेशन','कब और किस थाने में साइबर अपराध की शिकायत दर्ज की गई बताएं।FIR नंबर और जाँच स्थिति बताएं।कार्रवाई असंतोषजनक क्यों है बताएं।SP से निगरानी और त्वरित कार्रवाई का अनुरोध करें।'),requires_legal_disclaimer:0,disclaimer_text:null},
  {office_type:'block',name_hindi:'मुखिया प्रमाण पत्र आवेदन',name_english:'Mukhiya Certificate',keywords:JSON.stringify(['मुखिया','head','certificate','पंचायत']),required_fields:wb(['village','panchayat_name','purpose']),prompt_template:pa('block','मुखिया प्रमाण पत्र आवेदन','गाँव और पंचायत का नाम बताएं।प्रमाण पत्र का प्रयोजन बताएं।ग्राम पंचायत से मुखिया प्रमाण पत्र निर्गत करने का अनुरोध करें।'),requires_legal_disclaimer:0,disclaimer_text:null},
  {office_type:'school',name_hindi:'अभिभावक बैठक अनुरोध',name_english:'Parent-Teacher Meeting Request',keywords:JSON.stringify(['अभिभावक','parent','meeting','बैठक']),required_fields:wb(['school_name','class_name','roll_number','reason','preferred_date']),prompt_template:pa('school','अभिभावक बैठक अनुरोध','विद्यालय, कक्षा और रोल नंबर बताएं।बैठक का कारण और पसंदीदा तारीख बताएं।अभिभावक-शिक्षक बैठक का अनुरोध करें।'),requires_legal_disclaimer:0,disclaimer_text:null},
  {office_type:'sdo',name_hindi:'जाति प्रमाण पत्र अपील',name_english:'Caste Certificate Appeal',keywords:JSON.stringify(['जाति','caste','appeal','अपील']),required_fields:wb(['certificate_type','lower_office_name','rejection_date','rejection_reason','appeal_grounds']),prompt_template:p('sdo','जाति प्रमाण पत्र अपील','किस कार्यालय ने कब और क्यों जाति प्रमाण पत्र अस्वीकृत किया बताएं।अपील के आधार और दस्तावेज़ बताएं।SDO से पुनर्विचार का अनुरोध करें।'),requires_legal_disclaimer:0,disclaimer_text:null},
  {office_type:'bdo',name_hindi:'कृषि उपकरण अनुदान आवेदन',name_english:'Farm Equipment Subsidy',keywords:JSON.stringify(['कृषि','farm','equipment','subsidy','अनुदान']),required_fields:wb(['farmer_name','land_area','equipment_type','equipment_cost','bank_account_last4']),prompt_template:pa('bdo','कृषि उपकरण अनुदान आवेदन','किसान का नाम और भूमि क्षेत्रफल बताएं।उपकरण प्रकार और लागत बताएं।बैंक का नाम, शाखा और खाते के अंतिम चार अंक बताएं।पात्रतानुसार अनुदान स्वीकृत करने का अनुरोध करें।'),requires_legal_disclaimer:0,disclaimer_text:null},
  {office_type:'bank',name_hindi:'शिक्षा ऋण आवेदन',name_english:'Education Loan Application',keywords:JSON.stringify(['education','loan','शिक्षा','college']),required_fields:wb(['bank_name','branch','course_name','institute_name','course_fee','annual_income','co_applicant_name']),prompt_template:pa('bank','शिक्षा ऋण आवेदन','बैंक और शाखा का नाम बताएं।पाठ्यक्रम, संस्थान और शुल्क बताएं।पारिवारिक आय और सह-आवेदक का नाम दें।शिक्षा ऋण स्वीकृत करने का अनुरोध करें।'),requires_legal_disclaimer:0,disclaimer_text:null},
  {office_type:'transport',name_hindi:'ड्राइविंग लाइसेंस सुधार आवेदन',name_english:'Driving Licence Correction',keywords:JSON.stringify(['ड्राइविंग','driving','licence','license','लाइसेंस','correction','सुधार','परिवहन','transport']),required_fields:wb(['licence_number','correction_type','current_info','correct_info','dob','address']),prompt_template:pa('block','ड्राइविंग लाइसेंस सुधार आवेदन','ड्राइविंग लाइसेंस नंबर बताएं।क्या सुधार चाहिए और गलत/सही जानकारी दें।परिवहन विभाग से लाइसेंस में सुधार का अनुरोध करें।'),requires_legal_disclaimer:0,disclaimer_text:null},
  {office_type:'transport',name_hindi:'डुप्लीकेट ड्राइविंग लाइसेंस आवेदन',name_english:'Duplicate Driving Licence',keywords:JSON.stringify(['ड्राइविंग','driving','licence','license','लाइसेंस','डुप्लीकेट','duplicate','खोया','lost','परिवहन','transport']),required_fields:wb(['licence_number','loss_date','loss_reason','dob','address']),prompt_template:pa('block','डुप्लीकेट ड्राइविंग लाइसेंस आवेदन','ड्राइविंग लाइसेंस नंबर और खोने की तिथि व कारण बताएं।परिवहन विभाग से डुप्लीकेट लाइसेंस जारी करने का अनुरोध करें।'),requires_legal_disclaimer:0,disclaimer_text:null},
  {office_type:'transport',name_hindi:'ड्राइविंग लाइसेंस नवीनीकरण आवेदन',name_english:'Driving Licence Renewal',keywords:JSON.stringify(['ड्राइविंग','driving','licence','license','लाइसेंस','renewal','नवीनीकरण','expiry','परिवहन','transport']),required_fields:wb(['licence_number','expiry_date','medical_certificate','dob','address']),prompt_template:pa('block','ड्राइविंग लाइसेंस नवीनीकरण आवेदन','ड्राइविंग लाइसेंस नंबर और समाप्ति तिथि बताएं।मेडिकल प्रमाण पत्र संलग्न करें।परिवहन विभाग से लाइसेंस नवीनीकरण का अनुरोध करें।'),requires_legal_disclaimer:0,disclaimer_text:null},
  {office_type:'transport',name_hindi:'ड्राइविंग लाइसेंस नाम परिवर्तन आवेदन',name_english:'Driving Licence Name Change',keywords:JSON.stringify(['ड्राइविंग','driving','licence','license','लाइसेंस','name','नाम','change','परिवहन','transport']),required_fields:wb(['licence_number','old_name','new_name','change_reason','dob']),prompt_template:pa('block','ड्राइविंग लाइसेंस नाम परिवर्तन आवेदन','ड्राइविंग लाइसेंस नंबर और पुराना/नया नाम बताएं।परिवहन विभाग से नाम परिवर्तन का अनुरोध करें।'),requires_legal_disclaimer:0,disclaimer_text:null},
  {office_type:'dc',name_hindi:'फसल बीमा दावा आवेदन',name_english:'Crop Insurance Claim',keywords:JSON.stringify(['फसल','crop','insurance','बीमा','claim','दावा','नुकसान','agriculture','कृषि']),required_fields:wb(['insurance_policy_number','insurance_company','crop_type','land_area','incident_date','damage_description','estimated_loss','bank_account_last4']),prompt_template:pa('dc','फसल बीमा दावा आवेदन','फसल बीमा पॉलिसी नंबर और कंपनी का नाम बताएं।किस फसल का, कब और क्यों नुकसान हुआ बताएं।PM फसल बीमा योजना के तहत दावा राशि स्वीकृत करने का अनुरोध करें।'),requires_legal_disclaimer:0,disclaimer_text:null},
  {office_type:'co',name_hindi:'जमीन पर अवैध कब्जा शिकायत',name_english:'Illegal Land Possession Complaint',keywords:JSON.stringify(['जमीन','कब्जा','possession','अवैध','illegal','अतिक्रमण','encroachment','land','भूमि']),required_fields:wb(['khata_number','khasra_number','mouja_name','encroacher_name','encroacher_father_name','encroacher_village','encroachment_details','since_when','previous_complaints']),prompt_template:p('co','जमीन पर अवैध कब्जा शिकायत','खसरा/खाता नंबर और मौजा बताएं।अतिक्रमणकर्ता की पूरी पहचान और कब से कब्जा है बताएं।राजस्व अधिकारी से स्थलीय निरीक्षण कर बेदखली का अनुरोध करें।'),requires_legal_disclaimer:0,disclaimer_text:null},
  {office_type:'pwd',name_hindi:'बिजली बिल भुगतान अपडेट शिकायत',name_english:'Bill Payment Update Complaint',keywords:JSON.stringify(['बिजली','electricity','बिल','bill','payment','भुगतान','update','लंबित','शिकायत']),required_fields:wb(['consumer_number','payment_date','payment_amount','transaction_id','bill_number']),prompt_template:p('pwd','बिजली बिल भुगतान अपडेट शिकायत','उपभोक्ता संख्या और बिल नंबर बताएं।भुगतान तिथि, राशि और ट्रांजेक्शन ID दें।भुगतान के बावजूद बिल अपडेट न होने की समस्या बताएं।जाँच कर बिल अपडेट करने का अनुरोध करें।'),requires_legal_disclaimer:0,disclaimer_text:null},
  {office_type:'bdo',name_hindi:'वृद्धावस्था पेंशन आवेदन',name_english:'Old Age Pension Application',keywords:JSON.stringify(['वृद्धा','old age','pension','पेंशन','senior','वृद्धावस्था','सामाजिक']),required_fields:wb(['age','income','bpl_status','bank_account_last4']),prompt_template:pa('bdo','वृद्धावस्था पेंशन आवेदन','आयु, आय और BPL स्थिति बताएं।बैंक का नाम, शाखा और खाते के अंतिम चार अंक बताएं।पात्रतानुसार वृद्धावस्था पेंशन स्वीकृत करने का अनुरोध करें।'),requires_legal_disclaimer:0,disclaimer_text:null},
  {office_type:'bdo',name_hindi:'विधवा पेंशन आवेदन',name_english:'Widow Pension Application',keywords:JSON.stringify(['विधवा','widow','pension','पेंशन','महिला','women','सामाजिक','social']),required_fields:wb(['age','husband_death_date','income','marital_status','bank_account_last4']),prompt_template:pa('bdo','विधवा पेंशन आवेदन','आयु, पति की मृत्यु तिथि और वैवाहिक स्थिति बताएं।आय और बैंक का नाम, शाखा और खाते के अंतिम चार अंक बताएं।पात्रतानुसार विधवा पेंशन स्वीकृत करने का अनुरोध करें।'),requires_legal_disclaimer:0,disclaimer_text:null},
  {office_type:'dc',name_hindi:'पुलिस कार्रवाई RTI आवेदन',name_english:'Police Action RTI',keywords:JSON.stringify(['RTI','police','पुलिस','action','कार्रवाई','information']),required_fields:wb(['police_station_name','complaint_date','information_requested','time_period','format_required','ipo_details']),prompt_template:pa('dc','पुलिस कार्रवाई RTI आवेदन','RTI Act 2005 के तहत आवेदन।किस थाने से किस तिथि की शिकायत पर कार्रवाई की जानकारी चाहिए बताएं।IPO विवरण दें।'),requires_legal_disclaimer:0,disclaimer_text:null},
  {office_type:'court',name_hindi:'दोषपूर्ण उत्पाद शिकायत',name_english:'Defective Product Complaint',keywords:JSON.stringify(['defective','product','दोषपूर्ण','उत्पाद','consumer','उपभोक्ता','शिकायत','warranty']),required_fields:wb(['product_name','purchase_date','purchase_amount','seller_name','seller_address','defect_description','relief_sought']),prompt_template:p('court','दोषपूर्ण उत्पाद शिकायत','उत्पाद का नाम, खरीद तिथि और राशि बताएं।विक्रेता का नाम-पता दें।दोष का विस्तृत विवरण और माँगी गई राहत बताएं।प्रमाण दस्तावेज़ संलग्न करें।'),requires_legal_disclaimer:1,disclaimer_text:'यह एक प्रारूप मात्र है। जटिल कानूनी मामलों के लिए कृपया वकील से सलाह लें।'},
];
